### ISSUE TITLE
How to use this wp-customizer-utlilities in my theme?

### ISSUE THREAD

**Issue by Ebrahim6** [proteusthemes/wp-customizer-utilities#12]
I cant understand how to implement this in my theme. I know adding sections, control, settings, no problem there as I have added many options in my theme already. I can not understand which file to include in functions.php? or is there other ways that were outlined already? I'd be glad to get help from you.

**Comment by capuderg** [comment]
Hi,

the PHP composer will autoload the classes from this composer package, so you don't have to include anything else into your theme. Add it via PHP composer and start using the classes in your customizer file, for whatever you plan on using it.

The instructions on how to use it can be found in the main readme file: https://github.com/proteusthemes/wp-customizer-utilities
